name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'your-node-version'  # Specify your Node.js version (e.g., '16.x')

      - name: Install Dependencies
        run: npm install 

      - name: Build
        run: npm run build  # This will use your existing build script

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # or ./build, depending on your webpack output folder
